### ISSUE TITLE
namespace name 'INumber<>' 

### ISSUE THREAD

**Issue by tru01** [Ayman-Elfaki/XRobot#1]
Just downloaded your Project to start learning about BLE and VS.
I build the projet with VS 2022 preview (MAUI)
And I get:

Error	CS0246	The type or namespace name 'INumber<>' could not be found (are you missing a using directive or an assembly reference?)	XRobot (net6.0-android), XRobot (net6.0-ios)	C:\Users\User\source\repos\XRobot\src\Mobile\XRobot\Helpers\Extensions.cs	19	Active

Please kindly advice, I'm totally lost here, Br Cindy

**Comment by Ayman-Elfaki** [comment]
I think you just need to update the nuget package. check the latest commit [latest commit](https://github.com/Ayman-Elfaki/XRobot/commit/05003a0fc21a50eb7305102dd7e7188c9050deca)
